plugins:
  - jest
  - jest-dom
  - testing-library
env:
  browser: true
  es2021: true
extends: 
  - "eslint:recommended"
  - "airbnb-base"
  - "plugin:testing-library/dom"
  - "plugin:jest-dom/recommended"
  - "plugin:jest/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
