plugins:
  - jest-dom
  - testing-library
env:
  browser: true
  es2021: true
extends: 
  - eslint:recommended
  - airbnb-base
  - plugin:testing-library/recommended
  - plugin:jest-dom/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
